cmake_minimum_required(VERSION 3.16)
project(HelloQt LANGUAGES CXX)
set(CMAKE_AUTOMOC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Qt6 REQUIRED COMPONENTS Core Network Gui Widgets)
add_executable(hello main.cpp)
# Copy pass1.json next to the generated executable
configure_file(pass1.json pass1.json COPYONLY)
target_link_libraries(hello PRIVATE Qt6::Core Qt6::Network Qt6::Gui Qt6::Widgets)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
